In [3]:
#Sort, Search & Counting Functions.

In [2]:
import numpy as np

In [4]:
arr = np.array([4,3,4,5,6,72, 3,3, 455, 5,6,6])

In [5]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [6]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [7]:
np.searchsorted(arr, 34)

12

In [8]:
np.searchsorted(arr, 34)

12

In [9]:
arr1 = np.array([0, 345, 454,0,0,0,0,0])

In [11]:
np.count_nonzero(arr1)

2

In [15]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [16]:
np.where(arr > 6)

(array([5, 8]),)

In [17]:
np.extract(arr>6, arr)

array([ 72, 455])

In [18]:
#Numpy - Byte Swapping

In [19]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [20]:
arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616,   432345564227567616])

In [21]:
#Numpy - Copies & Views

In [22]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [23]:
a = np.copy(arr)

In [24]:
b = arr.view()

In [29]:
b = arr

In [26]:
a

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [27]:
b[0]

4

In [28]:
b[0] = 67

In [30]:
#NUmpy - Matrx

In [32]:
import numpy.matlib as nm

In [33]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [34]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [36]:
#Numpy - Linear Algebra

In [37]:
arr1 = np.random.randint([[2,3],[4,5]])

In [38]:
arr2 = np.random.randint([[5,3], [2,5]])

In [39]:
np.do(arr1,arr2)

AttributeError: module 'numpy' has no attribute 'do'

In [40]:
arr1@arr2

array([[1, 0],
       [3, 4]])