In [ ]:
#Numpy - Array Manipulation.

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10, (3,4))

In [3]:
arr

array([[7, 4, 7, 7],
       [3, 7, 2, 1],
       [2, 9, 1, 3]])

In [4]:
arr.reshape(6,2)

array([[7, 4],
       [7, 7],
       [3, 7],
       [2, 1],
       [2, 9],
       [1, 3]])

In [5]:
arr.reshape(2, 6)

array([[7, 4, 7, 7, 3, 7],
       [2, 1, 2, 9, 1, 3]])

In [6]:
arr.T

array([[7, 3, 2],
       [4, 7, 9],
       [7, 2, 1],
       [7, 1, 3]])

In [7]:
arr

array([[7, 4, 7, 7],
       [3, 7, 2, 1],
       [2, 9, 1, 3]])

In [8]:
arr.flatten()

array([7, 4, 7, 7, 3, 7, 2, 1, 2, 9, 1, 3])

In [9]:
arr1 = np.array([1,2,3,3,4])

In [10]:
arr1.ndim

1

In [11]:
np.expand_dims(arr1, axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [13]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 3, 4]])

In [14]:
arr

array([[7, 4, 7, 7],
       [3, 7, 2, 1],
       [2, 9, 1, 3]])

In [15]:
np.squeeze(arr) #no squeeze in terms of multiple elements

array([[7, 4, 7, 7],
       [3, 7, 2, 1],
       [2, 9, 1, 3]])

In [16]:
data = np.array([[1], [2], [3]])

In [17]:
data

array([[1],
       [2],
       [3]])

In [19]:
np.squeeze(data)

array([1, 2, 3])

In [20]:
arr1

array([1, 2, 3, 3, 4])

In [21]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [23]:
np.roll(arr1, 2)

array([3, 4, 1, 2, 3])

In [24]:
arr1

array([1, 2, 3, 3, 4])

In [25]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [26]:
#Numpy - Binary Operators

In [27]:
arr1 = np.random.randint(1, 10, (3,4))

In [28]:
arr2 = np.random.randint(1, 10, (3,4))

In [29]:
arr1

array([[7, 9, 9, 4],
       [7, 8, 1, 3],
       [1, 9, 6, 6]])

In [30]:
arr2

array([[5, 3, 6, 7],
       [1, 3, 9, 5],
       [4, 4, 3, 2]])

In [31]:
arr1 + arr2

array([[12, 12, 15, 11],
       [ 8, 11, 10,  8],
       [ 5, 13,  9,  8]])

In [32]:
arr1*arr2

array([[35, 27, 54, 28],
       [ 7, 24,  9, 15],
       [ 4, 36, 18, 12]])

In [33]:
arr1/arr2

array([[1.4       , 3.        , 1.5       , 0.57142857],
       [7.        , 2.66666667, 0.11111111, 0.6       ],
       [0.25      , 2.25      , 2.        , 3.        ]])

In [34]:
arr1-arr2

array([[ 2,  6,  3, -3],
       [ 6,  5, -8, -2],
       [-3,  5,  3,  4]])

In [35]:
arr1%arr2

array([[2, 0, 3, 4],
       [0, 2, 1, 3],
       [1, 1, 0, 0]])

In [37]:
arr1 & arr2

array([[5, 1, 0, 4],
       [1, 0, 1, 1],
       [0, 0, 2, 2]])

In [38]:
arr1 ** 2

array([[49, 81, 81, 16],
       [49, 64,  1,  9],
       [ 1, 81, 36, 36]])

In [39]:
arr1 ** arr2

array([[ 16807,    729, 531441,  16384],
       [     7,    512,      1,    243],
       [     1,   6561,    216,     36]])

In [40]:
arr1 & arr2

array([[5, 1, 0, 4],
       [1, 0, 1, 1],
       [0, 0, 2, 2]])

In [41]:
arr1

array([[7, 9, 9, 4],
       [7, 8, 1, 3],
       [1, 9, 6, 6]])

In [42]:
arr2

array([[5, 3, 6, 7],
       [1, 3, 9, 5],
       [4, 4, 3, 2]])

In [78]:
~arr1

array([[ -8, -10, -10,  -5],
       [ -8,  -9,  -2,  -4],
       [ -2, -10,  -7,  -7]])

In [44]:
arr1|arr2                                               

array([[ 7, 11, 15,  7],
       [ 7, 11,  9,  7],
       [ 5, 13,  7,  6]])

In [45]:
arr1>arr2

array([[ True,  True,  True, False],
       [ True,  True, False, False],
       [False,  True,  True,  True]])

In [46]:
#Numpy - String Function

In [48]:
arr = np.array(["Sudh", "Kumar"])

In [49]:
arr

array(['Sudh', 'Kumar'], dtype='<U5')

In [50]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [53]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [54]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [55]:
#Numpy - Mathematical Functions

In [56]:
arr1

array([[7, 9, 9, 4],
       [7, 8, 1, 3],
       [1, 9, 6, 6]])

In [57]:
np.sin(arr1)

array([[ 0.6569866 ,  0.41211849,  0.41211849, -0.7568025 ],
       [ 0.6569866 ,  0.98935825,  0.84147098,  0.14112001],
       [ 0.84147098,  0.41211849, -0.2794155 , -0.2794155 ]])

In [58]:
np.cos(arr1)

array([[ 0.75390225, -0.91113026, -0.91113026, -0.65364362],
       [ 0.75390225, -0.14550003,  0.54030231, -0.9899925 ],
       [ 0.54030231, -0.91113026,  0.96017029,  0.96017029]])

In [62]:
np.tanh(arr1)

array([[0.99999834, 0.99999997, 0.99999997, 0.9993293 ],
       [0.99999834, 0.99999977, 0.76159416, 0.99505475],
       [0.76159416, 0.99999997, 0.99998771, 0.99998771]])

In [63]:
np.log10(arr1)

array([[0.84509804, 0.95424251, 0.95424251, 0.60205999],
       [0.84509804, 0.90308999, 0.        , 0.47712125],
       [0.        , 0.95424251, 0.77815125, 0.77815125]])

In [64]:
np.exp(arr1)

array([[1.09663316e+03, 8.10308393e+03, 8.10308393e+03, 5.45981500e+01],
       [1.09663316e+03, 2.98095799e+03, 2.71828183e+00, 2.00855369e+01],
       [2.71828183e+00, 8.10308393e+03, 4.03428793e+02, 4.03428793e+02]])

In [66]:
np.sqrt(arr1)

array([[2.64575131, 3.        , 3.        , 2.        ],
       [2.64575131, 2.82842712, 1.        , 1.73205081],
       [1.        , 3.        , 2.44948974, 2.44948974]])

In [67]:
np.power(arr1, 2)

array([[49, 81, 81, 16],
       [49, 64,  1,  9],
       [ 1, 81, 36, 36]])

In [69]:
np.mean(arr1)

5.833333333333333

In [71]:
np.median(arr1)

6.5

In [72]:
np.median(arr1)

6.5

In [73]:
np.std(arr1)

2.823512391016236

In [74]:
np.var(arr1)

7.972222222222222

In [75]:
np.min(arr1)

1

In [76]:
np.max(arr1)

9