In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [4]:
ar = np.array(l)

In [5]:
ar

array([1, 2, 3, 4])

In [8]:
len(ar)

4

In [6]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
len(np.array([[1,2],[3,4]]))

2

In [10]:
np.asarray(l)

array([1, 2, 3, 4])

In [13]:
a = [2,3,4]

In [15]:
np.asanyarray(a)

array([2, 3, 4])

In [16]:
b = np.matrix(l)

In [17]:
b

matrix([[1, 2, 3, 4]])

In [ ]:
#matrix by default 2 dimension
#matrix is subset of array

In [18]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [19]:
a = np.array(l)

In [20]:
a

array([1, 2, 3, 4])

In [21]:
c = a

In [22]:
c

array([1, 2, 3, 4])

In [23]:
a

array([1, 2, 3, 4])

In [25]:
c[0] = 100

In [26]:
c[0]

100

In [27]:
a[0]

100

In [28]:
d = np.copy(a)

In [29]:
d

array([100,   2,   3,   4])

In [30]:
a

array([100,   2,   3,   4])

In [31]:
a[1] = 400

In [32]:
a

array([100, 400,   3,   4])

In [33]:
d

array([100,   2,   3,   4])

In [34]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [35]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [37]:
iterable = (i*i for i in range(5))

In [38]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [41]:
np.fromstring('234 567', sep=' ')

array([234., 567.])

In [42]:
np.fromstring('234,567', sep=',')

array([234., 567.])

In [43]:
#Numpy - Data Types

In [44]:
l = [2,3,4,5,6]

In [45]:
ar = np.array(l)

In [46]:
ar

array([2, 3, 4, 5, 6])

In [47]:
ar.ndim

1

In [48]:
ar2 = np.array([[1,2,3,4],[5,6,7,8]])

In [49]:
ar2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
ar2.ndim

2

In [51]:
ar.size

5

In [52]:
ar2.size

8

In [54]:
ar.shape

(5,)

In [53]:
ar2.shape

(2, 4)

In [56]:
ar.dtype

dtype('int64')

In [57]:
ar2.dtype

dtype('int64')

In [58]:
ar22 = np.array([(1.4, 45, 45), (23, 45, 66)])

In [59]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [60]:
ar22.dtype

dtype('float64')

In [62]:
list(range(5))

[0, 1, 2, 3, 4]

In [63]:
list(range(0.1, 5)) #therefore no floating numbers

TypeError: 'float' object cannot be interpreted as an integer

In [64]:
#so to tackle this arange|

In [65]:
np.arange(2.3, 5.6)

array([2.3, 3.3, 4.3, 5.3])

In [66]:
np.arange(2.3, 5.6, 0.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [67]:
list(np.arange(2.3, 5.6, 0.3)) #you can also use fraction instead of decimal number

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [68]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [69]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [70]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
np.zeros((3, 4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [73]:
ar4 = np.zeros((3,4,2,3))

In [74]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [75]:
ar4.ndim

4

In [76]:
np.ones(4)

array([1., 1., 1., 1.])

In [77]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [79]:
on = np.ones((2,3,2))

In [80]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [81]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [82]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [83]:
np.empty((3,5))

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])

In [84]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [85]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [87]:
np.logspace(2,5,10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [89]:
arr = np.random.randn(3,4)

In [90]:
arr

array([[ 0.28477675,  0.22162284,  0.49737211,  1.47074477],
       [ 0.90261384, -0.92898927, -1.80558527,  0.80079945],
       [-0.33154885, -0.68188377,  0.40612627,  0.05882954]])

In [91]:
import pandas as pd

In [92]:
pd.DataFrame(arr)

0         1         2         3
0  0.284777  0.221623  0.497372  1.470745
1  0.902614 -0.928989 -1.805585  0.800799
2 -0.331549 -0.681884  0.406126  0.058830

In [93]:
np.random.rand(3,4)

array([[0.05758322, 0.63324285, 0.77277412, 0.35830426],
       [0.26380982, 0.21383307, 0.82112914, 0.6913929 ],
       [0.18646288, 0.029382  , 0.08400886, 0.09251593]])

In [95]:
np.random.randint(5,10, (3,4))

array([[5, 5, 9, 9],
       [8, 6, 6, 5],
       [8, 9, 5, 6]])

In [96]:
arr55 = np.random.randint(50,100, (10,15))

In [97]:
arr55

array([[74, 63, 51, 89, 78, 98, 98, 68, 73, 91, 94, 73, 76, 69, 92],
       [90, 80, 81, 99, 77, 89, 68, 96, 95, 63, 76, 72, 69, 96, 78],
       [50, 91, 54, 94, 97, 63, 64, 75, 77, 86, 65, 75, 63, 74, 74],
       [63, 65, 52, 64, 66, 56, 74, 69, 52, 66, 96, 81, 96, 83, 70],
       [97, 56, 68, 89, 54, 57, 74, 92, 88, 60, 99, 58, 91, 72, 55],
       [64, 71, 92, 74, 95, 92, 79, 55, 78, 68, 96, 99, 78, 66, 79],
       [87, 58, 84, 99, 88, 98, 62, 75, 96, 68, 65, 59, 57, 84, 95],
       [61, 51, 59, 60, 71, 80, 83, 76, 60, 72, 60, 92, 67, 89, 62],
       [84, 78, 93, 96, 88, 99, 85, 91, 53, 54, 52, 86, 59, 56, 54],
       [59, 96, 90, 97, 67, 97, 80, 75, 58, 85, 57, 71, 51, 92, 61]])

In [99]:
df1 = pd.DataFrame(arr55)

In [100]:
df1

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14
0  74  63  51  89  78  98  98  68  73  91  94  73  76  69  92
1  90  80  81  99  77  89  68  96  95  63  76  72  69  96  78
2  50  91  54  94  97  63  64  75  77  86  65  75  63  74  74
3  63  65  52  64  66  56  74  69  52  66  96  81  96  83  70
4  97  56  68  89  54  57  74  92  88  60  99  58  91  72  55
5  64  71  92  74  95  92  79  55  78  68  96  99  78  66  79
6  87  58  84  99  88  98  62  75  96  68  65  59  57  84  95
7  61  51  59  60  71  80  83  76  60  72  60  92  67  89  62
8  84  78  93  96  88  99  85  91  53  54  52  86  59  56  54
9  59  96  90  97  67  97  80  75  58  85  57  71  51  92  61

In [104]:
df1.to_csv('testpart1.csv')

In [105]:
ar6 = np.random.rand(3,4)

In [106]:
ar6

array([[0.05943618, 0.62225406, 0.60328421, 0.96398176],
       [0.87588049, 0.80181118, 0.38421559, 0.67140896],
       [0.8978024 , 0.43216714, 0.62949449, 0.61855125]])

In [107]:
ar6.reshape(6,2)

array([[0.05943618, 0.62225406],
       [0.60328421, 0.96398176],
       [0.87588049, 0.80181118],
       [0.38421559, 0.67140896],
       [0.8978024 , 0.43216714],
       [0.62949449, 0.61855125]])

In [110]:
ar6 = ar6.reshape(6,-1)

In [111]:
ar6

array([[0.05943618, 0.62225406],
       [0.60328421, 0.96398176],
       [0.87588049, 0.80181118],
       [0.38421559, 0.67140896],
       [0.8978024 , 0.43216714],
       [0.62949449, 0.61855125]])

In [112]:
ar6[1]

array([0.60328421, 0.96398176])

In [113]:
ar6[1][1]

0.9639817648414374

In [116]:
ar6[2:5]

array([[0.87588049, 0.80181118],
       [0.38421559, 0.67140896],
       [0.8978024 , 0.43216714]])

In [117]:
ar6[2:5,1]

array([0.80181118, 0.67140896, 0.43216714])

In [119]:
ar7 = np.random.randint(1,100, (5,5))

In [120]:
ar7

array([[78, 21, 23, 74, 14],
       [97, 57, 51, 55, 24],
       [ 1,  4, 23, 39, 38],
       [78, 25, 35, 57, 17],
       [20,  7,  8, 26,  1]])

In [121]:
ar7>50

array([[ True, False, False,  True, False],
       [ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [ True, False, False,  True, False],
       [False, False, False, False, False]])

In [122]:
ar7[ar7>50]

array([78, 74, 97, 57, 51, 55, 78, 57])

In [123]:
ar7

array([[78, 21, 23, 74, 14],
       [97, 57, 51, 55, 24],
       [ 1,  4, 23, 39, 38],
       [78, 25, 35, 57, 17],
       [20,  7,  8, 26,  1]])

In [124]:
ar7[2:4, (1,2)]

array([[ 4, 23],
       [25, 35]])

In [125]:
ar7[0]

array([78, 21, 23, 74, 14])

In [126]:
ar7[0, [0]]

array([78])

In [127]:
ar7[0][0] = 500

In [128]:
ar7

array([[500,  21,  23,  74,  14],
       [ 97,  57,  51,  55,  24],
       [  1,   4,  23,  39,  38],
       [ 78,  25,  35,  57,  17],
       [ 20,   7,   8,  26,   1]])

In [131]:
ar1 = np.random.randint(1,3, (3,3))
ar2 = np.random.randint(1,3, (3,3))

In [132]:
ar1

array([[1, 2, 2],
       [1, 2, 1],
       [2, 1, 2]])

In [133]:
ar2

array([[2, 1, 2],
       [2, 1, 2],
       [1, 2, 2]])

In [134]:
ar1+ar2

array([[3, 3, 4],
       [3, 3, 3],
       [3, 3, 4]])

In [135]:
ar1-ar2

array([[-1,  1,  0],
       [-1,  1, -1],
       [ 1, -1,  0]])

In [136]:
ar1/ar2

array([[0.5, 2. , 1. ],
       [0.5, 2. , 0.5],
       [2. , 0.5, 1. ]])

In [138]:
ar1*ar2 #it is not matrix mutlplication

array([[2, 2, 4],
       [2, 2, 2],
       [2, 2, 4]])

In [139]:
ar1@ar2

array([[ 8,  7, 10],
       [ 7,  5,  8],
       [ 8,  7, 10]])

In [140]:
ar1/0

/var/folders/kl/h33z80hx4978lqcftcf7sxr40000gn/T/ipykernel_78922/3042774750.py:1: RuntimeWarning: divide by zero encountered in divide
  ar1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [141]:
ar1 + 100

array([[101, 102, 102],
       [101, 102, 101],
       [102, 101, 102]])

In [143]:
ar1**2

array([[1, 4, 4],
       [1, 4, 1],
       [4, 1, 4]])

# Numpy BroadCasting

In [145]:
arr = np.zeros((4,4))

In [146]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [149]:
row = np.array([1,2,3,4])

In [152]:
row.shape

(4,)

In [150]:
row

array([1, 2, 3, 4])

In [151]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [153]:
row.T #it is one dimension so it will not be transpose

array([1, 2, 3, 4])

In [ ]:
#convert it into 2D by adding []

In [154]:
col = np.array([[1,2,3,4]])

In [155]:
col.T 

array([[1],
       [2],
       [3],
       [4]])

In [156]:
col.T + arr #Hence, Column wise broadcasting

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [160]:
arr1 = np.random.randint(1,4, (3,4))

In [161]:
arr1

array([[1, 1, 2, 3],
       [2, 3, 2, 2],
       [2, 3, 2, 2]])

In [162]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 1.41421356, 1.41421356],
       [1.41421356, 1.73205081, 1.41421356, 1.41421356]])

In [163]:
np.exp(arr1)

array([[ 2.71828183,  2.71828183,  7.3890561 , 20.08553692],
       [ 7.3890561 , 20.08553692,  7.3890561 ,  7.3890561 ],
       [ 7.3890561 , 20.08553692,  7.3890561 ,  7.3890561 ]])

In [165]:
np.log10(arr1)

array([[0.        , 0.        , 0.30103   , 0.47712125],
       [0.30103   , 0.47712125, 0.30103   , 0.30103   ],
       [0.30103   , 0.47712125, 0.30103   , 0.30103   ]])